name: Test

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                ruby-version:
                    - "3.1"
                rustup-toolchain:
                    - stable

        steps:
            - uses: actions/checkout@v3

            - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
              with:
                  rustup-toolchain: ${{ matrix.rustup-toolchain }}
                  ruby-version: ${{ matrix.ruby-version }}
                  cache-version: v2
                  bundler-cache: true
                  cargo-cache: true
                  cargo-cache-extra-path: |
                      examples/rust_blank/tmp/
                      examples/complete_object/tmp/
                      examples/custom_exception_ruby/tmp/
                      examples/custom_exception_rust/tmp/

            - name: Run tests
              run: cargo test --doc
